CREATE TABLE songs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  artist VARCHAR(20) NOT NULL,
  label VARCHAR(20) NOT NULL,
  released INTEGER NOT NULL
  );



CREATE TABLE `playlists` (
  `id` INT(11) NOT NULL,
  `isPrivate` TINYINT NOT NULL,
  `name` VARCHAR(100) NULL,
  `ownerId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ownerId_idx` (`ownerId` ASC),
  CONSTRAINT `ownerId`
    FOREIGN KEY (`ownerId`)
    REFERENCES `sys`.`user` (`userId`)
    ON DELETE CASCADE);


CREATE TABLE `playlist_song`(
  `playlist_id` INT(11) NOT NULL,
  `song_id` INT(11) NOT NULL,
  PRIMARY KEY (`playlist_id`, `song_id`),
  INDEX `song_id_idx` (`song_id` ASC),
  CONSTRAINT `song_id`
    FOREIGN KEY (`song_id`)
    REFERENCES `sys`.`songs` (`id`)
    ON UPDATE CASCADE,
  CONSTRAINT `playlist_id`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `sys`.`playlists` (`id`)
    ON UPDATE CASCADE);